"""baseline schema

Revision ID: 7a369f628967
Revises: 
Create Date: 2026-06-14 01:32:28.406958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base  # UTCDateTime 自訂型別


# revision identifiers, used by Alembic.
revision: str = '7a369f628967'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('line_user_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('start_at', app.models.base.UTCDateTime(), nullable=False),
    sa.Column('end_at', app.models.base.UTCDateTime(), nullable=False),
    sa.Column('category', sa.Enum('meeting', 'focus', 'meal', 'personal', name='eventcategory'), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('attendees', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'live', 'done', name='eventstatus'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('notified_at', app.models.base.UTCDateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_start_at'), ['start_at'], unique=False)

    op.create_table('reminders',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subtitle', sa.String(length=200), nullable=True),
    sa.Column('trigger_at', app.models.base.UTCDateTime(), nullable=True),
    sa.Column('recurrence', sa.String(length=100), nullable=True),
    sa.Column('kind', sa.Enum('meeting', 'birthday', 'bill', 'health', name='reminderkind'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('fired_at', app.models.base.UTCDateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('due_at', app.models.base.UTCDateTime(), nullable=True),
    sa.Column('priority', sa.Enum('high', 'medium', 'low', name='taskpriority'), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', 'tool', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    op.drop_table('tasks')
    op.drop_table('reminders')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_start_at'))

    op.drop_table('events')
    op.drop_table('conversations')
    # ### end Alembic commands ###
